### ISSUE TITLE
Broker only returns publisher on topic creation

### ISSUE THREAD

**Issue by jdblack** [sauerbraten/pubsub#1]
Hello!  I've been playing with pubsub as part of my adventures in learning golang.    I'm curious about the intent behind the decision to on https://github.com/sauerbraten/pubsub/blob/master/broker.go#L60  to return nil instead of the existing publisher?

**Comment by sauerbraten** [comment]
It is done this way because createTopicIfNotExists() is used in Subscribe(), and the caller of Subscribe() needs to know whether a publisher for that topic already exists:
- if the caller gets a nil publisher, that tells it that somebody already publishes data for that topic and that there is nothing more to do
- if the returned publisher is non-nil, that means it was newly created and the caller of Subscribe() has to somehow start a goroutine that uses the returned publisher to publish data for that topic

That's exactly what's happening in the example code in the README: https://github.com/sauerbraten/pubsub#example

Does this answer your question?

**Comment by jdblack** [comment]
Yes sir.  That was my understanding of the code.

My thought at the time was that I was imagining a pattern in which several go-routines may wish to publish to the same topic.    Later on I realized that I can just pass the publisher into my publishers, 
 rather than the broker.
